version: '3'

services:
  postgres-airflow:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pssd
      POSTGRES_USER: airflowuser
      POSTGRES_DB: airflowdb

      AIRFLOW_SCHEMA: airflow
    expose:
      - 5432
    restart: always

    volumes:
      - ./script_postgress:/docker-entrypoint-initdb.d

  postgres-dbt:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pssd
      POSTGRES_USER: dbtuser
      POSTGRES_DB: dbtdb
      DBT_RAW_DATA_SCHEMA: dbt_raw_data

      DBT_SCHEMA: dbt
    expose:
      - 5432
    restart: always
    volumes:
      - ./data:/opt/iowa/data

  airflow:
    build: .
    restart: always
    environment: 
      DBT_PROFILES_DIR: /opt/iowa/dbt
      AIRFLOW_HOME: /opt/iowa/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/iowa/airflow/dags
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__PARALLELISM: 4
      AIRFLOW__CORE__DAG_CONCURRENCY: 4
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 4
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      # AIRFLOW__ADMIN__HIDE_SENSITIVE_VARIABLE_FIELDS: False
      # Postgres details need to match with the values defined in the postgres-airflow service
      POSTGRES_USER: airflowuser
      POSTGRES_PASSWORD: pssd
      POSTGRES_HOST: postgres-airflow
      POSTGRES_PORT: 5432
      POSTGRES_DB: airflowdb
      # postgres-dbt connection details. Required for the inital loading of seed data
      # Credentials need to match with service postgres-dbt
      DBT_POSTGRES_PASSWORD: pssd
      DBT_POSTGRES_USER : dbtuser
      DBT_POSTGRES_DB : dbtdb
      DBT_DBT_SCHEMA: dbt
      DBT_DBT_RAW_DATA_SCHEMA: dbt_raw_data
      DBT_POSTGRES_HOST: postgres-dbt

      GOOGLE_APPLICATION_CREDENTIALS: /.google/credentials/google_credentials_iowa.json
      AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: 'google-cloud-platform://?extra__google_cloud_platform__key_path=/.google/credentials/google_credentials_iowa.json'
      GCP_PROJECT_ID: 'iowa-project-de'
      GCP_GCS_BUCKET: 'iowa_data_lake'
      GCP_BQ_DATASET: 'iowa_data'
      DEPLOY_STATUS: 'dev'

    depends_on:
      - postgres-airflow
      - postgres-dbt
    ports:
      - 8000:8080
    volumes:
      - ./dbt:/opt/iowa/dbt
      - ./data:/opt/iowa/data
      - ./airflow:/opt/iowa/airflow
      - ~/.google/credentials/:/.google/credentials:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres-airflow
      - postgres-dbt